### ISSUE TITLE
Error: certificate has expired

### ISSUE THREAD

**Issue by rafiques** [smart-on-fhir/smart-launcher#24] opened 2019-10-28 13:44 UTC
We are getting this error during the application launch with fhir version **R2**.

**Comment by vlad-ignatov** [comment] 2019-10-28 16:37
For some reason our “automatic” lets-encrypt certificate renewal failed to renew automatically this time. The issue is now fixed. We apologize for the inconvenience!

**Closed by vlad-ignatov** 2019-10-28 16:37 UTC
